export const mockBooks = [
    {
        id: 1,
        isbn: "978-0-13-235088-4",
        title: "Clean Code",
        format: "e-book",
        shortDescription: "Guía práctica para escribir código limpio y mantenible.",
        authors: ["Robert C. Martin"],
        price: 45.99,
        publisher: "Prentice Hall",
        cover: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg"
    },
    {
        id: 2,
        isbn: "978-0-201-61622-4",
        title: "The Pragmatic Programmer",
        format: "e-book",
        shortDescription: "Consejos prácticos para programadores profesionales.",
        authors: ["Andrew Hunt", "David Thomas"],
        price: 49.99,
        publisher: "Addison-Wesley",
        cover: "https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg"
    },
    {
        id: 3,
        isbn: "978-0-201-63361-0",
        title: "Design Patterns",
        format: "Físico",
        shortDescription: "Referencia esencial sobre patrones de diseño.",
        authors: ["Erich Gamma", "Richard Helm", "Ralph Johnson", "John Vlissides"],
        price: 54.99,
        publisher: "Addison-Wesley",
        cover: "https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg"
    },
    {
        id: 4,
        isbn: "978-0-321-12742-6",
        title: "Domain-Driven Design",
        format: "Físico",
        shortDescription: "Guía sobre modelado de dominios complejos.",
        authors: ["Eric Evans"],
        price: 62.99,
        publisher: "Addison-Wesley",
        cover: "https://covers.openlibrary.org/b/isbn/9780321127426-L.jpg"
    },
    {
        id: 5,
        isbn: "978-0-13-475759-9",
        title: "Refactoring",
        format: "Físico",
        shortDescription: "Técnicas para mejorar código existente.",
        authors: ["Martin Fowler"],
        price: 58.5,
        publisher: "Addison-Wesley",
        cover: "https://covers.openlibrary.org/b/isbn/9780134757599-L.jpg"
    },
    {
        id: 6,
        isbn: "978-1-491-94765-9",
        title: "Designing Data-Intensive Applications",
        format: "e-book",
        shortDescription: "Diseño de sistemas de datos escalables.",
        authors: ["Martin Kleppmann"],
        price: 64.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491947659-L.jpg"
    },
    {
        id: 7,
        isbn: "978-1-449-37332-0",
        title: "Learning Python",
        format: "Físico",
        shortDescription: "Guía completa para aprender Python.",
        authors: ["Mark Lutz"],
        price: 79.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg"
    },
    {
        id: 8,
        isbn: "978-1-59327-928-8",
        title: "Python Crash Course",
        format: "e-book",
        shortDescription: "Curso práctico de Python basado en proyectos.",
        authors: ["Eric Matthes"],
        price: 39.95,
        publisher: "No Starch Press",
        cover: "https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg"
    },
    {
        id: 9,
        isbn: "978-1-491-91646-6",
        title: "Fluent Python",
        format: "Físico",
        shortDescription: "Python avanzado con enfoque idiomático.",
        authors: ["Luciano Ramalho"],
        price: 69.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491916466-L.jpg"
    },
    {
        id: 10,
        isbn: "978-1-491-94600-8",
        format: "Físico",
        title: "JavaScript: The Definitive Guide",
        shortDescription: "Referencia completa de JavaScript.",
        authors: ["David Flanagan"],
        price: 59.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491946008-L.jpg"
    },
    {
        id: 11,
        isbn: "978-1-61729-586-7",
        title: "Node.js Design Patterns",
        format: "e-book",
        shortDescription: "Patrones de diseño para aplicaciones Node.js.",
        authors: ["Mario Casciaro", "Luciano Mammino"],
        price: 52.99,
        publisher: "Manning Publications",
        cover: "https://covers.openlibrary.org/b/isbn/9781617295867-L.jpg"
    },
    {
        id: 12,
        isbn: "978-1-4842-8149-3",
        title: "Beginning React",
        format: "e-book",
        shortDescription: "Introducción práctica al desarrollo con React.",
        authors: ["Greg Lim"],
        price: 34.99,
        publisher: "Apress",
        cover: "https://covers.openlibrary.org/b/isbn/9781484281493-L.jpg"
    },
    {
        id: 13,
        isbn: "978-1-4842-8144-8",
        title: "Full Stack Development with Spring Boot and React",
        format: "Físico",
        shortDescription: "Desarrollo full stack con Spring Boot y React.",
        authors: ["Juha Hinkula"],
        price: 44.99,
        publisher: "Apress",
        cover: "https://covers.openlibrary.org/b/isbn/9781484281448-L.jpg"
    },
    {
        id: 14,
        isbn: "978-1-4842-8791-4",
        title: "Pro ASP.NET Core 6",
        format: "Físico",
        shortDescription: "Desarrollo web profesional con ASP.NET Core.",
        authors: ["Adam Freeman"],
        price: 74.99,
        publisher: "Apress",
        cover: "https://covers.openlibrary.org/b/isbn/9781484287914-L.jpg"
    },
    {
        id: 15,
        isbn: "978-1-4920-3843-9",
        title: "Kubernetes: Up and Running",
        format: "e-book",
        shortDescription: "Guía práctica para iniciar con Kubernetes.",
        authors: ["Brendan Burns", "Joe Beda", "Kelsey Hightower"],
        price: 47.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781492038439-L.jpg"
    },
    {
        id: 16,
        isbn: "978-1-4920-0673-9",
        title: "Terraform: Up and Running",
        format: "Físico",
        shortDescription: "Infraestructura como código con Terraform.",
        authors: ["Yevgeniy Brikman"],
        price: 55.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781492006739-L.jpg"
    },
    {
        id: 17,
        isbn: "978-1-59327-950-9",
        title: "Automate the Boring Stuff with Python",
        format: "e-book",
        shortDescription: "Automatización práctica con Python.",
        authors: ["Al Sweigart"],
        price: 36.99,
        publisher: "No Starch Press",
        cover: "https://covers.openlibrary.org/b/isbn/9781593279509-L.jpg"
    },
    {
        id: 18,
        isbn: "978-1-4920-7619-7",
        title: "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
        format: "Físico",
        shortDescription: "Machine learning práctico con Python.",
        authors: ["Aurélien Géron"],
        price: 72.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781492076197-L.jpg"
    },
    {
        id: 19,
        isbn: "978-1-4842-7366-9",
        title: "Practical Deep Learning",
        format: "e-book",
        shortDescription: "Introducción práctica al deep learning.",
        authors: ["Ronald T. Kneusel"],
        price: 48.99,
        publisher: "No Starch Press",
        cover: "https://covers.openlibrary.org/b/isbn/9781484273669-L.jpg"
    },
    {
        id: 20,
        isbn: "978-1-4919-1425-0",
        title: "Data Science from Scratch",
        format: "e-book",
        shortDescription: "Ciencia de datos desde cero con Python.",
        authors: ["Joel Grus"],
        price: 46.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491914250-L.jpg"
    },
    {
        id: 21,
        isbn: "978-1-4919-5766-0",
        title: "Python for Data Analysis",
        format: "e-book",
        shortDescription: "Análisis de datos con pandas y NumPy.",
        authors: ["Wes McKinney"],
        price: 59.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491957660-L.jpg"
    },
    {
        id: 22,
        isbn: "978-0-13-461099-3",
        title: "Artificial Intelligence",
        format: "Físico",
        shortDescription: "Referencia académica de inteligencia artificial.",
        authors: ["Stuart Russell", "Peter Norvig"],
        price: 89.99,
        publisher: "Pearson",
        cover: "https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg"
    },
    {
        id: 23,
        isbn: "978-0-262-04630-5",
        title: "Introduction to Algorithms",
        format: "Físico",
        shortDescription: "Referencia completa sobre algoritmos.",
        authors: ["Thomas H. Cormen", "Charles E. Leiserson", "Ronald L. Rivest", "Clifford Stein"],
        price: 94.99,
        publisher: "MIT Press",
        cover: "https://covers.openlibrary.org/b/isbn/9780262046305-L.jpg"
    },
    {
        id: 24,
        isbn: "978-0-13-110362-7",
        title: "The C Programming Language",
        format: "Físico",
        shortDescription: "Referencia clásica del lenguaje C.",
        authors: ["Brian W. Kernighan", "Dennis M. Ritchie"],
        price: 42.99,
        publisher: "Prentice Hall",
        cover: "https://covers.openlibrary.org/b/isbn/9780131103627-L.jpg"
    },
    {
        id: 25,
        isbn: "978-0-321-35668-0",
        title: "Effective Java",
        format: "Físico",
        shortDescription: "Buenas prácticas avanzadas para Java.",
        authors: ["Joshua Bloch"],
        price: 51.99,
        publisher: "Addison-Wesley",
        cover: "https://covers.openlibrary.org/b/isbn/9780321356680-L.jpg"
    },
    {
        id: 26,
        isbn: "978-1-4919-5326-2",
        title: "Head First Java",
        format: "e-book",
        shortDescription: "Introducción visual y práctica a Java.",
        authors: ["Kathy Sierra", "Bert Bates", "Trisha Gee"],
        price: 59.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491953262-L.jpg"
    },
    {
        id: 27,
        isbn: "978-1-59327-584-6",
        title: "Eloquent JavaScript",
        format: "e-book",
        shortDescription: "Introducción moderna a JavaScript.",
        authors: ["Marijn Haverbeke"],
        price: 38.99,
        publisher: "No Starch Press",
        cover: "https://covers.openlibrary.org/b/isbn/9781593275846-L.jpg"
    },
    {
        id: 28,
        isbn: "978-1-59327-828-1",
        title: "The Rust Programming Language",
        format: "e-book",
        shortDescription: "Guía práctica para aprender Rust.",
        authors: ["Steve Klabnik", "Carol Nichols"],
        price: 44.99,
        publisher: "No Starch Press",
        cover: "https://covers.openlibrary.org/b/isbn/9781593278281-L.jpg"
    },
    {
        id: 29,
        isbn: "978-1-4920-7853-3",
        title: "Software Architecture: The Hard Parts",
        format: "Físico",
        shortDescription: "Análisis de decisiones difíciles en arquitectura.",
        authors: ["Neal Ford", "Mark Richards", "Pramod Sadalage", "Zhamak Dehghani"],
        price: 61.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781492078533-L.jpg"
    },
    {
        id: 30,
        isbn: "978-1-4919-3969-0",
        title: "Building Microservices",
        format: "e-book",
        shortDescription: "Diseño e implementación de microservicios.",
        authors: ["Sam Newman"],
        price: 63.99,
        publisher: "O'Reilly Media",
        cover: "https://covers.openlibrary.org/b/isbn/9781491939690-L.jpg"
    }
];